export const equipmentAllocationRooms = [
  {
    roomId: 'ROOM-A101',
    roomName: 'A101',
    campus: 'Cơ sở Quận 1',
    capacity: 20,
    allocationStatus: 'Đang sử dụng',
    equipment: [
      {
        roomId: 'ROOM-A101',
        roomName: 'A101',
        capacity: 20,
        equipmentId: 'EQ-1001',
        equipmentCode: 'TB001',
        equipmentName: 'Máy chiếu Epson EB-X06',
        category: 'Máy chiếu',
        quantity: 1,
        condition: 'Tốt',
        allocationStatus: 'Đang sử dụng',
        allocatedDate: '19/08/2026',
        assignedBy: 'Nguyễn Văn A',
        note: 'Thiết bị chính của phòng.',
        allocationHistory: [
          { date: '19/08/2026', fromRoom: 'Kho', toRoom: 'A101', reason: 'Đưa vào sử dụng', assignedBy: 'Nguyễn Văn A' },
          { date: '10/06/2026', fromRoom: 'Kho', toRoom: 'A101', reason: 'Bổ sung thiết bị', assignedBy: 'Trần Văn B' },
        ],
      },
      {
        roomId: 'ROOM-A101',
        roomName: 'A101',
        capacity: 20,
        equipmentId: 'EQ-1002',
        equipmentCode: 'TB002',
        equipmentName: 'Laptop giáo viên Dell 5420',
        category: 'Máy tính',
        quantity: 1,
        condition: 'Tốt',
        allocationStatus: 'Đang sử dụng',
        allocatedDate: '19/08/2026',
        assignedBy: 'Nguyễn Văn A',
        note: 'Dùng cho giáo viên đứng lớp.',
        allocationHistory: [
          { date: '19/08/2026', fromRoom: 'Kho', toRoom: 'A101', reason: 'Đưa vào sử dụng', assignedBy: 'Nguyễn Văn A' },
        ],
      },
      {
        roomId: 'ROOM-A101',
        roomName: 'A101',
        capacity: 20,
        equipmentId: 'EQ-1003',
        equipmentCode: 'TB003',
        equipmentName: 'Loa Bluetooth JBL',
        category: 'Âm thanh',
        quantity: 2,
        condition: 'Tốt',
        allocationStatus: 'Đang sử dụng',
        allocatedDate: '19/08/2026',
        assignedBy: 'Nguyễn Văn A',
        note: 'Âm lượng ổn định.',
        allocationHistory: [
          { date: '19/08/2026', fromRoom: 'Kho', toRoom: 'A101', reason: 'Bổ sung âm thanh', assignedBy: 'Nguyễn Văn A' },
        ],
      },
      {
        roomId: 'ROOM-A101',
        roomName: 'A101',
        capacity: 20,
        equipmentId: 'EQ-1004',
        equipmentCode: 'TB004',
        equipmentName: 'Micro không dây Shure',
        category: 'Âm thanh',
        quantity: 2,
        condition: 'Cần kiểm tra',
        allocationStatus: 'Tạm giữ',
        allocatedDate: '18/08/2026',
        assignedBy: 'Nguyễn Văn A',
        note: 'Một micro nhiễu nhẹ cuối buổi.',
        allocationHistory: [
          { date: '18/08/2026', fromRoom: 'Kho', toRoom: 'A101', reason: 'Thay micro cũ', assignedBy: 'Nguyễn Văn A' },
        ],
      },
    ],
  },
  {
    roomId: 'ROOM-A102',
    roomName: 'A102',
    campus: 'Cơ sở Quận 1',
    capacity: 18,
    allocationStatus: 'Đang sử dụng',
    equipment: [
      {
        roomId: 'ROOM-A102',
        roomName: 'A102',
        capacity: 18,
        equipmentId: 'EQ-1005',
        equipmentCode: 'TB005',
        equipmentName: 'Máy chiếu Epson EB-X51',
        category: 'Máy chiếu',
        quantity: 1,
        condition: 'Tốt',
        allocationStatus: 'Đang sử dụng',
        allocatedDate: '16/08/2026',
        assignedBy: 'Trần Văn B',
        note: '',
        allocationHistory: [
          { date: '16/08/2026', fromRoom: 'Kho', toRoom: 'A102', reason: 'Đưa vào sử dụng', assignedBy: 'Trần Văn B' },
        ],
      },
      {
        roomId: 'ROOM-A102',
        roomName: 'A102',
        capacity: 18,
        equipmentId: 'EQ-1006',
        equipmentCode: 'TB006',
        equipmentName: 'Webcam Logitech C920',
        category: 'Thiết bị online',
        quantity: 1,
        condition: 'Tốt',
        allocationStatus: 'Đang sử dụng',
        allocatedDate: '16/08/2026',
        assignedBy: 'Trần Văn B',
        note: '',
        allocationHistory: [
          { date: '16/08/2026', fromRoom: 'Kho', toRoom: 'A102', reason: 'Phục vụ lớp online', assignedBy: 'Trần Văn B' },
        ],
      },
    ],
  },
  {
    roomId: 'ROOM-A103',
    roomName: 'A103',
    campus: 'Cơ sở Quận 1',
    capacity: 22,
    allocationStatus: 'Đang điều chuyển',
    equipment: [
      {
        roomId: 'ROOM-A103',
        roomName: 'A103',
        capacity: 22,
        equipmentId: 'EQ-1007',
        equipmentCode: 'TB007',
        equipmentName: 'Bảng tương tác ViewSonic',
        category: 'Bảng tương tác',
        quantity: 1,
        condition: 'Đang bảo trì',
        allocationStatus: 'Đang điều chuyển',
        allocatedDate: '12/08/2026',
        assignedBy: 'Lê Hoàng Vy',
        note: 'Đang chờ kỹ thuật cân chỉnh.',
        allocationHistory: [
          { date: '12/08/2026', fromRoom: 'B202', toRoom: 'A103', reason: 'Điều chuyển theo lịch lớp', assignedBy: 'Lê Hoàng Vy' },
        ],
      },
    ],
  },
  {
    roomId: 'ROOM-B201',
    roomName: 'B201',
    campus: 'Cơ sở Bình Thạnh',
    capacity: 24,
    allocationStatus: 'Đang sử dụng',
    equipment: [
      {
        roomId: 'ROOM-B201',
        roomName: 'B201',
        capacity: 24,
        equipmentId: 'EQ-1008',
        equipmentCode: 'TB008',
        equipmentName: 'Bộ chia HDMI',
        category: 'Phụ kiện',
        quantity: 1,
        condition: 'Tốt',
        allocationStatus: 'Đang sử dụng',
        allocatedDate: '14/08/2026',
        assignedBy: 'Nguyễn Văn A',
        note: '',
        allocationHistory: [
          { date: '14/08/2026', fromRoom: 'Kho', toRoom: 'B201', reason: 'Bổ sung thiết bị trình chiếu', assignedBy: 'Nguyễn Văn A' },
        ],
      },
      {
        roomId: 'ROOM-B201',
        roomName: 'B201',
        capacity: 24,
        equipmentId: 'EQ-1009',
        equipmentCode: 'TB009',
        equipmentName: 'Loa trợ giảng JTS',
        category: 'Âm thanh',
        quantity: 2,
        condition: 'Hỏng',
        allocationStatus: 'Tạm giữ',
        allocatedDate: '11/08/2026',
        assignedBy: 'Nguyễn Văn A',
        note: 'Loa rè, cần báo bảo trì.',
        allocationHistory: [
          { date: '11/08/2026', fromRoom: 'A101', toRoom: 'B201', reason: 'Chuyển theo yêu cầu lớp tối', assignedBy: 'Nguyễn Văn A' },
        ],
      },
    ],
  },
  {
    roomId: 'ROOM-B202',
    roomName: 'B202',
    campus: 'Cơ sở Bình Thạnh',
    capacity: 16,
    allocationStatus: 'Chưa phân bổ',
    equipment: [],
  },
  {
    roomId: 'ROOM-C301',
    roomName: 'C301',
    campus: 'Cơ sở Quận 3',
    capacity: 25,
    allocationStatus: 'Đang sử dụng',
    equipment: [
      {
        roomId: 'ROOM-C301',
        roomName: 'C301',
        capacity: 25,
        equipmentId: 'EQ-1010',
        equipmentCode: 'TB010',
        equipmentName: 'Máy chiếu Epson EB-W06',
        category: 'Máy chiếu',
        quantity: 1,
        condition: 'Tốt',
        allocationStatus: 'Đang sử dụng',
        allocatedDate: '13/08/2026',
        assignedBy: 'Phạm Minh Hạnh',
        note: 'Phục vụ lớp IELTS buổi tối.',
        allocationHistory: [
          { date: '13/08/2026', fromRoom: 'Kho', toRoom: 'C301', reason: 'Đưa vào sử dụng', assignedBy: 'Phạm Minh Hạnh' },
        ],
      },
      {
        roomId: 'ROOM-C301',
        roomName: 'C301',
        capacity: 25,
        equipmentId: 'EQ-1011',
        equipmentCode: 'TB011',
        equipmentName: 'Laptop giáo viên HP ProBook',
        category: 'Máy tính',
        quantity: 1,
        condition: 'Tốt',
        allocationStatus: 'Đang sử dụng',
        allocatedDate: '13/08/2026',
        assignedBy: 'Phạm Minh Hạnh',
        note: '',
        allocationHistory: [
          { date: '13/08/2026', fromRoom: 'Kho', toRoom: 'C301', reason: 'Bổ sung máy giáo viên', assignedBy: 'Phạm Minh Hạnh' },
        ],
      },
    ],
  },
  {
    roomId: 'ROOM-C302',
    roomName: 'C302',
    campus: 'Cơ sở Quận 3',
    capacity: 20,
    allocationStatus: 'Tạm giữ',
    equipment: [
      {
        roomId: 'ROOM-C302',
        roomName: 'C302',
        capacity: 20,
        equipmentId: 'EQ-1012',
        equipmentCode: 'TB012',
        equipmentName: 'Loa kéo Dalton',
        category: 'Âm thanh',
        quantity: 1,
        condition: 'Cần kiểm tra',
        allocationStatus: 'Tạm giữ',
        allocatedDate: '09/08/2026',
        assignedBy: 'Lê Hoàng Vy',
        note: 'Cần kiểm tra pin trước khi dùng lại.',
        allocationHistory: [
          { date: '09/08/2026', fromRoom: 'C301', toRoom: 'C302', reason: 'Tạm giữ chờ kiểm tra', assignedBy: 'Lê Hoàng Vy' },
        ],
      },
    ],
  },
  {
    roomId: 'ROOM-D401',
    roomName: 'D401',
    campus: 'Cơ sở Thủ Đức',
    capacity: 30,
    allocationStatus: 'Đang sử dụng',
    equipment: [
      {
        roomId: 'ROOM-D401',
        roomName: 'D401',
        capacity: 30,
        equipmentId: 'EQ-1013',
        equipmentCode: 'TB013',
        equipmentName: 'Bảng tương tác Samsung Flip',
        category: 'Bảng tương tác',
        quantity: 1,
        condition: 'Tốt',
        allocationStatus: 'Đang sử dụng',
        allocatedDate: '08/08/2026',
        assignedBy: 'Trần Văn B',
        note: 'Phòng demo và lớp kỹ năng.',
        allocationHistory: [
          { date: '08/08/2026', fromRoom: 'Kho', toRoom: 'D401', reason: 'Trang bị phòng demo', assignedBy: 'Trần Văn B' },
        ],
      },
      {
        roomId: 'ROOM-D401',
        roomName: 'D401',
        capacity: 30,
        equipmentId: 'EQ-1014',
        equipmentCode: 'TB014',
        equipmentName: 'Micro cổ ngỗng',
        category: 'Âm thanh',
        quantity: 2,
        condition: 'Tốt',
        allocationStatus: 'Đang sử dụng',
        allocatedDate: '08/08/2026',
        assignedBy: 'Trần Văn B',
        note: '',
        allocationHistory: [
          { date: '08/08/2026', fromRoom: 'Kho', toRoom: 'D401', reason: 'Bổ sung âm thanh', assignedBy: 'Trần Văn B' },
        ],
      },
    ],
  },
  {
    roomId: 'ROOM-D402',
    roomName: 'D402',
    campus: 'Cơ sở Thủ Đức',
    capacity: 18,
    allocationStatus: 'Đang điều chuyển',
    equipment: [
      {
        roomId: 'ROOM-D402',
        roomName: 'D402',
        capacity: 18,
        equipmentId: 'EQ-1015',
        equipmentCode: 'TB015',
        equipmentName: 'Máy chiếu BenQ MX560',
        category: 'Máy chiếu',
        quantity: 1,
        condition: 'Đang bảo trì',
        allocationStatus: 'Đang điều chuyển',
        allocatedDate: '07/08/2026',
        assignedBy: 'Nguyễn Văn A',
        note: 'Đang chuyển sang phòng thay thế sau bảo trì.',
        allocationHistory: [
          { date: '07/08/2026', fromRoom: 'A103', toRoom: 'D402', reason: 'Điều chuyển thiết bị sau bảo trì', assignedBy: 'Nguyễn Văn A' },
        ],
      },
    ],
  },
  {
    roomId: 'ROOM-E501',
    roomName: 'E501',
    campus: 'Cơ sở Gò Vấp',
    capacity: 28,
    allocationStatus: 'Đang sử dụng',
    equipment: [
      {
        roomId: 'ROOM-E501',
        roomName: 'E501',
        capacity: 28,
        equipmentId: 'EQ-1016',
        equipmentCode: 'TB016',
        equipmentName: 'Camera họp Logitech MeetUp',
        category: 'Thiết bị online',
        quantity: 1,
        condition: 'Tốt',
        allocationStatus: 'Đang sử dụng',
        allocatedDate: '05/08/2026',
        assignedBy: 'Lê Hoàng Vy',
        note: 'Phục vụ lớp hybrid.',
        allocationHistory: [
          { date: '05/08/2026', fromRoom: 'Kho', toRoom: 'E501', reason: 'Mở lớp hybrid', assignedBy: 'Lê Hoàng Vy' },
        ],
      },
    ],
  },
  {
    roomId: 'ROOM-KHO-Q1',
    roomName: 'Kho Q1',
    campus: 'Cơ sở Quận 1',
    capacity: 0,
    allocationStatus: 'Chưa phân bổ',
    equipment: [
      {
        roomId: 'ROOM-KHO-Q1',
        roomName: 'Kho Q1',
        capacity: 0,
        equipmentId: 'EQ-1017',
        equipmentCode: 'TB017',
        equipmentName: 'Remote máy chiếu dự phòng',
        category: 'Phụ kiện',
        quantity: 5,
        condition: 'Tốt',
        allocationStatus: 'Chưa phân bổ',
        allocatedDate: '01/08/2026',
        assignedBy: 'Kho thiết bị',
        note: 'Thiết bị dự phòng.',
        allocationHistory: [
          { date: '01/08/2026', fromRoom: 'Nhà cung cấp', toRoom: 'Kho Q1', reason: 'Nhập kho', assignedBy: 'Kho thiết bị' },
        ],
      },
    ],
  },
]

export const allocationEquipmentOptions = [
  { equipmentId: 'EQ-1001', equipmentCode: 'TB001', equipmentName: 'Máy chiếu Epson EB-X06', category: 'Máy chiếu', total: 10, allocated: 8 },
  { equipmentId: 'EQ-1002', equipmentCode: 'TB002', equipmentName: 'Laptop giáo viên Dell 5420', category: 'Máy tính', total: 6, allocated: 5 },
  { equipmentId: 'EQ-1003', equipmentCode: 'TB003', equipmentName: 'Loa Bluetooth JBL', category: 'Âm thanh', total: 12, allocated: 10 },
  { equipmentId: 'EQ-1004', equipmentCode: 'TB004', equipmentName: 'Micro không dây Shure', category: 'Âm thanh', total: 8, allocated: 6 },
]
