export const headerNotifications = [
  {
    id: 'NTF-BC-001',
    type: 'report',
    title: 'Báo cáo phân bổ giáo viên tháng 08/2026',
    message: 'Có 2 giáo viên đang thiếu tải và 2 giáo viên cần theo dõi quá tải.',
    time: '10 phút trước',
    createdAt: '2026-08-21 09:20',
    unread: true,
    priority: 'Cao',
    report: {
      code: 'BC-GV-082026',
      name: 'Báo cáo phân bổ giáo viên',
      period: 'Tháng 08/2026',
      campus: 'Tất cả cơ sở',
      owner: 'Phòng Giáo vụ',
      generatedAt: '21/08/2026 09:20',
      summary: 'Tổng hợp tải dạy theo tuần, số lớp đang phụ trách và khuyến nghị điều phối cho từng giáo viên.',
      metrics: [
        { label: 'Giáo viên', value: '7' },
        { label: 'Lớp đang học', value: '7' },
        { label: 'Thiếu tải', value: '2' },
        { label: 'Quá tải', value: '2' },
      ],
      findings: [
        'Phạm Minh Hạnh đạt 104.76% tải dạy, cần giảm hoặc chuyển bớt lớp Kids cuối tuần.',
        'Trần Bảo Ngọc hiện đạt 44.44% tải dạy, có thể ưu tiên nhận thêm lớp TOEIC tại Thủ Đức.',
        'Nguyễn Thùy Linh đang ở mức ổn định 85.71%, tiếp tục giữ tải hiện tại.',
      ],
    },
  },
  {
    id: 'NTF-TB-002',
    type: 'equipment',
    title: 'Thiết bị cần kiểm tra',
    message: 'Máy chiếu phòng B201 cần xác nhận tình trạng trước ca 18:30.',
    time: '35 phút trước',
    createdAt: '2026-08-21 08:55',
    unread: true,
    priority: 'Trung bình',
  },
  {
    id: 'NTF-LH-003',
    type: 'schedule',
    title: 'Lịch học có thay đổi phòng',
    message: 'Lớp IELTS09A chuyển từ A103 sang A105 trong buổi tối nay.',
    time: 'Hôm nay',
    createdAt: '2026-08-21 08:10',
    unread: false,
    priority: 'Thấp',
  },
]
